# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AWS DataOps Development Kit
email: aws-proserve-opensource@amazon.com
description: >- # this means to ignore newlines until "baseurl:"
  An open source development framework to help you build data workflows and modern data architecture on AWS.
repository: 'awslabs/aws-ddk'
baseurl: "/aws-ddk" # the subpath of your site, e.g. /blog
url: "https://github.com/awslabs/aws-ddk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
workshop_url: https://catalog.us-east-1.prod.workshops.aws/workshops/3644b48b-1d7c-43ef-a353-6edcd96385af/en-US
sdlf_workshop_url: https://catalog.us-east-1.prod.workshops.aws/workshops/28010662-4e98-48a7-a8ea-9e42aafa85f7/en-US
constructs_hub_url: https://constructs.dev/packages/aws-ddk-core/
legacy_versions:
- 0.1.0
- 0.2.0
- 0.3.0
- 0.4.0
- 0.5.1
- 0.6.0
- 0.6.1
- 0.6.2

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-tabs

include:
  - _static

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
