name: CFN Nag

on:
  workflow_dispatch:
  push:
    paths:
    - "cli/aws_ddk/data/cloudformation_templates/**"
    branches:
    - main
  pull_request:
    # paths:
    # - "cli/aws_ddk/data/cloudformation_templates/**"
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stelligent/cfn_nag@master
        with:
          input_path: cli/aws_ddk/data/cloudformation_templates
          extra_args: --ignore-fatal
      - name: Fail if cfn_nag scan contains failures
        run: |
              exit `grep Failures cfn_nag.out | awk '{ SUM += $3} END { print SUM }'`